version: "3.6"

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - "data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: friends_management
    networks:
      - friends_management
    ports:
      - "5433:5432"

  migration:
    build: .
    command: sh -c "./wait-for db:5432 -- sh migration.sh"
    volumes:
      - "./migrations:/go/src/app/migrations"
      - "./:/go/src/app"
    depends_on:
      - db
    networks:
      - friends_management

  app:
    build: .
    command: sh start.sh
    # entrypoint: /bin/sh
    volumes:
      - "./:/go/src/app"
    ports:
      - "3000:3000"
    networks:
      - friends_management
    depends_on:
      - migration
      - db

volumes:
  data:

networks:
  friends_management:
    driver: "bridge"

